### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by CinemaMC** [TRSoftware1/GambleBarVersion#2]
[00:10:44 ERROR]: Error occurred while enabling GambleBarPro v2.1.0 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "String.equalsIgnoreCase(String)" because the return value of "org.bukkit.configuration.file.FileConfiguration.getString(String)" is null
        at GambleBarPro-2.1.0.jar/com.trsoftware.gamblebarpro.bar.EconomyManager.setEconomyTypes(EconomyManager.java:30) ~[GambleBarPro-2.1.0.jar:?]
        at GambleBarPro-2.1.0.jar/com.trsoftware.gamblebarpro.GambleBar.onEnable(GambleBar.java:112) ~[GambleBarPro-2.1.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:754) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:516) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[00:10:44 INFO]: [GambleBarPro] Disabling GambleBarPro v2.1.0

**Comment by TRSoftware1** [comment]
Sorry I'm just now seeing this. In the future, please report issues in the Discord. This problem is caused by not having the most up to date config settings. I believe you're missing the "defaultEconomy" field.
